global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["sdmay26-37.ece.iastate.edu:8000"]
        labels:
          app: "coursegpt"
    metrics_path: "/metrics"
    scheme: "http"

  - job_name: "discord-bot"
    static_configs:
      - targets: ["sdmay26-37.ece.iastate.edu:9091"]
        labels:
          app: "coursegpt"
    metrics_path: "/metrics"
    scheme: "http"
